### ISSUE TITLE
一些代码和工程上的建议

### ISSUE THREAD

**Issue by ruibaby** [Shine-Theme/halo-theme-crux#2]
非常好看的主题，以下是一些关于代码和工程的建议：

1. 建议在开发阶段使用 prettier 格式化一下代码，或者使用 husky 之类的工具添加 git commit hook 实现提交的时候自动格式化。
2. 我注意到页面所用的图标都是使用的 svg，所以建议图标方案采用 iconify 的生态。项目使用了 Tailwindcss，我推荐使用 https://github.com/JensDll/tailwindcss-plugin-icons 插件，可以在编译的时候将 svg 构建到 css 中，使用方式可以参考：https://github.com/halo-dev/theme-earth
3. 在 page_github 模板中，我注意到需要在前端使用 GitHub 的 Token，这种方式非常不推荐，会导致 Token 泄露。我们是否可以完善一下 https://github.com/halo-sigs/plugin-repos 这个插件？这个插件可以在后端同步 GitHub 账号的仓库数据并提供给主题模板。

**Comment by Snuffel233** [comment]
非常有用的建议！

1. 我会继续提高代码规范性并在工作流中引入自动格式化
2. 图标设计不规范的问题将会在下个版本改善
3. 对于Token泄露问题，这点确实在设计之初欠考虑，我会在正式版本中加入显著提示，并且在接下来的几个星期里着手将https://github.com/halo-sigs/plugin-repos项目应用在本项目中

再次感谢，受益匪浅！

**Comment by ruibaby** [comment]
https://github.com/halo-sigs/plugin-repos

这个插件是我们在社区例会上为了演示插件开发而创建的，所以目前还不是很完善 :)

我们可以把这个插件完善一下，因为这个项目展示对于一些开发者的博客来说应该还是非常有用的。
